package policy

// This file defines the result of policy evaluation.
//
// A decision contains:
//
//   - whether the action is allowed
//   - whether approval is required
//   - whether the action is denied
//   - the reason for the decision
//
// The decision is generated by application policy, not by the LLM.
