package llm

// This file represents a structured tool call generated by the LLM.
//
// Example:
//
//   Tool:
//       find_delayed_orders
//
//   Arguments:
//       {
//           "delay_minutes": 30
//       }
//
// The tool call is only a request for execution.
//
// It must be validated and forwarded to the Host Project before any
// business operation occurs.
//
// The LLM is never trusted as the source of authorization or business
// truth.
